const data = {
    products: [
        {
            name: 'Cleveland Train poster',
            slug: 'cleveland-train-poster',
            category: 'poster',
            image: '/images/p1.jpg',
            price: 58,
            countInStock:10,
            brand: '8 Red Fish Creative',
            size: '20 x 30',
            rating: 4.5,
            numReviews: 10,
            description: '1930 Cleveland Train poster reprint',
        },
        {
            name: '1912 Cleveland map',
            slug: '1912-cleveland-map',
            category: 'map',
            image: '/images/p2.jpg',
            price: 78,
            countInStock:20,
            brand: 'Old Parlor Shop',
            size: '24 x 36',
            rating: 5.0,
            numReviews: 12,
            description: '1912 Cleveland map reprint',
        },
        {
            name: 'Mid-century Manhattan Map',
            slug: 'mid-century-manhattan-map',
            category: 'map',
            image: '/images/p3.jpg',
            price: 98,
            countInStock:0,
            brand: '8 Red Fish Creative',
            size: '16 x 48',
            rating: 5.0,
            numReviews: 90,
            description: 'Mid-century Manhattan Map reprint',
        },
        {
            name: '1912 World map',
            slug: '1912-world-map',
            category: 'map',
            image: '/images/p4.jpg',
            price: 108,
            countInStock:15,
            brand:'Old Parlor Shop',
            size: '30 x 40',
            rating: 5.0,
            numReviews: 30,
            description: '1912 World map reprint',
        },
        {
            name: '1810 Star chart',
            slug: '1810-star-chart',
            category: 'map',
            image: '/images/p5.jpg',
            price: 98,
            countInStock:30,
            brand: 'Old Parlor Shop',
            size: '24 x 36',
            rating: 5.0,
            numReviews: 100,
            description: '1810 Celestial Chart reprint',
        },
        {
            name: 'New York City subway',
            slug: 'new-york-city-subway',
            category: 'map',
            image: '/images/p6.jpg',
            price: 58,
            countInStock:12,
            brand: '8 Red Fish Creative',
            size: '20 x 30',
            rating: 5.0,
            numReviews: 101,
            description: 'Mid-century New York City subway',
        },
    ]
}
export default data;